"""creating cliente and transacao

Revision ID: a89509219124
Revises: 
Create Date: 2024-02-08 23:48:34.036627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89509219124'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('limite', sa.Integer(), nullable=True),
    sa.Column('saldo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=1), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_id'), 'transacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_id'), table_name='transacoes')
    op.drop_table('transacoes')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
